### PR TITLE
LPS-95339 Fix method description

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
Hey @rbohl,

if you have some doubts about my changes in https://github.com/rbohl/liferay-docs/pull/139/commits/8ad427a8accb9a68e0fec713793882f109e67ba1 please slack me.

Thx

**Comment by rbohl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rbohl** [comment]
Forwarded: https://github.com/sez11a/liferay-docs/pull/4424

**Comment by rbohl** [comment]
Thanks @rafaprax !

**Pull request closed without merging**
