### PR TITLE
LRDOCS-6591, form storage adapters

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-6591, converted the 7.1 forms storage adapters article to 7.2. I did not test any code yet, so if there were changes, I haven't detected them. I'll begin looking more closely at the code next. cc @jeyvison @natocesarrego

### CODE REVIEW

**Comment by rbohl** [comment]
bump @jeyvison. Has anything changed with the way we're doing form storage adapters in 7.2? If not this is probably ok to send for publication.

**Comment by jeyvison** [comment]
Hey @rbohl , It looks good. I have just one comment about it. Currently the StorageAdapter interface and the BaseStorageAdapter class are deprecated. Can we still lauch the decumentation based on it?

**Comment by rbohl** [comment]
@jeyvison is there any other way to do it? If not I'd say I should add a note (can we mention what will replace it, if anything?) and we can publish it.

Unless this is something we don't want to publish for 7.2?

**Comment by jeyvison** [comment]
@rbohl hmmm, i think for now we should keep as it is since we can't remove it yet( we are not in a major release). The classes already have a **@deprecated** annotation telling what are the replacements, if there is any. Do you think it's worth to add it to the documentation?

**Comment by rbohl** [comment]
Yeah, I think we can add that to the documentation. :+1:

I'll do that.

**Comment by jeyvison** [comment]
Thanks! :)

**Comment by rbohl** [comment]
@jeyvison how does this sound?

> **Note:** The `StorageAdapter` interface and it's abstract implementation, `BaseStorageAdapter`, are deprecated in @product-ver@, with no direct replacement. If you need a storage adapter, this is still the way to create one, but be aware that it will not be available in a future version.

**Comment by jeyvison** [comment]
@rbohl , The StorageAdapter interface does have a direct replacement, the **DDMStorageAdapter**.  Besides that, LGTM.

**Comment by rbohl** [comment]
Oh okay, got it, I misunderstood. Should we instead show devs how to use the `DDMStorageAdapter`?

**Comment by jeyvison** [comment]
Humm, no i think it's fine for them to use  Storage Adapter for now.

**Comment by rbohl** [comment]
Sent for publication: https://github.com/sez11a/liferay-docs/pull/4099

**Comment by medrag** [comment]
Hello, 
I'm using Liferay 7.2, and as you said before `BaseStorageAdapter` class is deprecated, can you please give us a clear implementation of the `DDMStorageAdapter` interface. Thank you

**Comment by rbohl** [comment]
@medrag `BaseStorageAdapter`, despite being deprecated with a direct replacement, is still the way to get this done, according to the Forms team (via the discussion above). That's why it's still the way we official document creating a storage adapter for the forms application: https://portal.liferay.dev/docs/7-2/customization/-/knowledge_base/c/form-storage-adapters#form-storage-adapters

**Comment by medrag** [comment]
@rbohl, thank you for your reply.
In fact i did use the 'BaseStorageAdapter' class and tried to implement a new storage type, but without success, the new storage option doesn't appear in the form settings modal and the server shows no errors.
Any hints on how to fix that ?. Thank you

**Comment by rbohl** [comment]
Hey @medrag , I'm not sure what the issue might be. My suggestion is to use one of these venues, and provide some details so folks can help:

1.  the forums: https://liferay.dev/forums
2.  our slack group: https://liferay.dev/chat

**Pull request closed without merging**
