### PR TITLE
LRDOCS-4617 Add content regarding the files .babelrc and .npmbundlerrc.

### PR DESCRIPTION
**Pull request by natocesarrego**
Hey @rbohl,

This is the most recent version of the article _Custom Form Field Types_. It includes the Time field code updated and tested on the bundle 7.1 GA1. In addition, I'd like to tell you the following:

- Can you please update the [reference](https://github.com/rbohl/liferay-docs/pull/89/commits/4f499f61adbfb396decb998c63c66cf3e78ebee1#diff-c59b8d360bae2735976a082a894b5f11R31) to the Time field source code?
- On this pull request, I added content about two files `.babelrc` and `.npmbundlerrc`. Basically, I mentioned them and put a link for more details, but I wasn't sure if this is enough, therefore feel free to raise a discussion about that. 🙂 

If you need anything else regarding this pull, please let me know.

Best.

### CODE REVIEW

**Comment by rbohl** [comment]
Merged locally.

My plan is to go through the articles and build the module using the code samples inside of a new Liferay Workspace. I'll let you know if I run into any problems.

**Comment by natocesarrego** [comment]
Ok, @rbohl. Thanks for the update! 😉

**Comment by natocesarrego** [comment]
Yes.

I didn't understand the following sentence:

> Following the instructions in the tutorial, I don't have these modules...

Which modules are that? Do you mean the node modules?

If you prefer, we can have a call and I can assist you in order to try to figure out what is going on.

Best.

**Comment by rbohl** [comment]
That was a typo, I meant _files_, not _modules_. Basically, we don't provide the necessary configuration in these files: `.npmbundlerrc`, `.babelrc`, and `package.json`. Should we add this? In all my time at Liferay I've never had to touch any of these files, so I'm not sure how familiar third party devs will be with them.

**Comment by natocesarrego** [comment]
Honestly, I was in doubt if we should mention these files, but I discussed with some Forms Front-end Engineers and they said that makes sense share this information with the developers. Nowadays, in the Front-end world, the files `.babelrc` and `package.json` are very common, therefore I understand that would be nice mention, but not go very deep on that.

Would you like to discuss more about it with the Front-end guys?

**Comment by rbohl** [comment]
I think the goal should be to document what's necessary to get the
module working. We don't need to go into detail about how to compose
these files in general, but if they're required to build a working build
and must be handwritten we should include just enough to get the module
built. Let me see if I can get what I need from your module, and I'll
let you know if I need more help on this. I'm on another task but should
be back to this by the end of the day.

**Comment by natocesarrego** [comment]
The three files don't need to be changed in order to make the module work. Besides, feel free to reach me as you need.

Best.

**Comment by rbohl** [comment]
https://github.com/natocesarrego/liferay-docs/pull/29

**Pull request closed without merging**
