### PR TITLE
LRDOCS-4617 Add the time field code mentioned in the articles.

### PR DESCRIPTION
**Pull request by natocesarrego**
Hey Russell,

I just would like to ask you to please update the link for the source code of the _time field_ project, which is mentioned on the article _Form Field Types_. If you have any question or need some clarification regarding this pull, please talk to me.

Thanks in advance.

### CODE REVIEW

**Comment by rbohl** [comment]
Merged locally. Thanks, Renato!

**Comment by rbohl** [comment]
@natocesarrego I got the time field type module to build by updating the com.liferay.gradle.plugins dependency. I can see the Time field in the Elements sidebar, but cannot add it to my form. No exceptions in the log, it just doesn't do anything. 

I'm working on 7.1 CE GA1 since we're publishing this for 7.1.

time-field

**Comment by natocesarrego** [comment]
Hi @rbohl,

I faced the same issue after deploy the Time field, but it was caused due to the lack of the prefix `dynamic-data-mapping` on this [line](https://github.com/rbohl/liferay-docs/blob/1c2918bad9e067595d906ea8610488a0a8624533/develop/tutorials/code/dynamic-data-mapping-type-time/bnd.bnd#L5) of the file _bnd.bnd_ and this [other line](https://github.com/rbohl/liferay-docs/blob/1c2918bad9e067595d906ea8610488a0a8624533/develop/tutorials/code/dynamic-data-mapping-type-time/package.json#L17) of the file _package.json_, but it's not your case. Probably, it's being caused due to an outdated dependency, code, etc. Anyway, I'll investigate it and get back to you soon.

Sorry for the issue. 😁

**Comment by natocesarrego** [comment]
Hey Russell,

Sad news. Besides the rework on the time field code, I'll need to update some things on this article, once all form fields modules were merged to a single module due to an automatic backport done by BChan. This backport wasn't intended, but it was done. Therefore, I'll need an extra time to deliver all these changes. I'm working on it right now.

Best.

**Comment by natocesarrego** [comment]
Hey @rbohl,

By the end of yesterday, I was able to recreate the time field module code and make it work on Liferay GA1 bundle. 🎉 🎉 

In addition, I decided to review all three articles included on this pull request to make sure there is no issue after the code update, therefore I'll do this review before send a new pull to you. Currently, I reviewed the first article and now I'll move on to check the second article. As soon as I finish all reviews, I let you know.

Thanks for your help! 😉

**Comment by rbohl** [comment]
Sounds good, thanks Renato!

**Comment by natocesarrego** [comment]
Hey @rbohl,

I'm closing this pull to send a new one updated.

Best.

**Pull request closed without merging**
