### PR TITLE
MOBILE-1137 Update FormScreenlet doc

### PR DESCRIPTION
**Pull request by victorlaerte**

### CODE REVIEW

**Comment by victorlaerte** [comment]
Hey @rbohl, after your review can you cherry pick for master too?

Thank you.

/cc @jeyvison

**Comment by rbohl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rbohl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rbohl** [comment]
@ngaskill where would this go in master?

**Comment by ngaskill** [comment]
@rbohl At present, nowhere. The Screens docs have not yet been ported to 7.2.

**Comment by rbohl** [comment]
Okay, I'll considered this finished then. @victorlaerte Once the port to 7.2 happens these changes will be picked up.

**Pull request merged**
