### PR TITLE
7.2 | LPS-90616 New Queries

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-90616

### CODE REVIEW

**Comment by lipusz** [comment]
Added TODO blocks (hidden)

**Comment by rbohl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rbohl** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rbohl** [comment]
Superceded: https://github.com/lipusz/liferay-docs/pull/34

**Pull request closed without merging**
